### ISSUE TITLE
Bug with the delete

### ISSUE THREAD

**Issue by rvallade** [rvallade/SmartConverter#7]
1. enter text like 123
2. change m to ft for the second units spinner
3. hit delete
   ==> error

java.lang.NumberFormatException: Invalid long: "403,54330"
at com.apps.romain.smartconverter.MainActivity.doConvert(MainActivity.java:350)
at com.apps.romain.smartconverter.MainActivity.access$200(MainActivity.java:18)
at com.apps.romain.smartconverter.MainActivity$5.onClick(MainActivity.java:187)

String result = ConvertUtils.convertir(new BigDecimal(textToConvert), converterFrom, converterTo);

NB: this doesn't seem to appear on genymotion...

**Comment by rvallade** [comment]
Possible cause it's that in french the decimal indicator is a comma where inn English this it's a point.
When the number is a double the combs is not interpreted well on a french device
